/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_barismeral_ports_SerialPort */

#ifndef _Included_com_github_barismeral_ports_SerialPort
#define _Included_com_github_barismeral_ports_SerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_barismeral_ports_SerialPort
 * Method:    openPort
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_github_barismeral_ports_SerialPort_openPort
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_github_barismeral_ports_SerialPort
 * Method:    closePort
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_github_barismeral_ports_SerialPort_closePort
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_github_barismeral_ports_SerialPort
 * Method:    setParam
 * Signature: (JIIII)Z
 */
JNIEXPORT jboolean JNICALL Java_com_github_barismeral_ports_SerialPort_setParam
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint);

/*
 * Class:     com_github_barismeral_ports_SerialPort
 * Method:    write
 * Signature: (J[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_github_barismeral_ports_SerialPort_write
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     com_github_barismeral_ports_SerialPort
 * Method:    read
 * Signature: (JI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_github_barismeral_ports_SerialPort_read
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_github_barismeral_ports_SerialPort
 * Method:    purgePort
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_github_barismeral_ports_SerialPort_purgePort
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
